version: '3'

services:
  web-hook:
    restart: 'always'
    working_dir: '/app'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - './:/app'
    env_file: '.env'
    environment:
    - NGINX_WEB_ROOT=/app/public
    - NGINX_PHP_FALLBACK=/index.php
    - NGINX_PHP_LOCATION=^/index\.php(/|$$)
    - APP_DEV_PERMITTED=1
    - SHELL_VERBOSITY=3
    ports:
    - "80:80"